# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('CODECOMP', 'Coding Competition'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], max_length=200)),
                ('date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
