# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160607_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='headline',
        ),
    ]
